;; TIM|(eval-when-compile
;; TIM|  (require 'color-theme))
;; TIM|
;; TIM|(defun color-theme-adam-chandra ()
;; TIM|  "Color theme by Adam Saunders, originally ripped off from somebody named Arneson"
;; TIM|  (interactive)
;; TIM|  (color-theme-install
;; TIM|   '(color-theme-adam-chandra
;; TIM|     ((background-color . "black")
;; TIM|      (background-mode . light)
;; TIM|      (background-toolbar-color . "#cf3ccf3ccf3c")
;; TIM|      (border-color . "#000000000000")
;; TIM|      (bottom-toolbar-shadow-color . "#79e77df779e7")
;; TIM|      (cursor-color . "Red")
;; TIM|      (foreground-color . "Beige")
;; TIM|      (top-toolbar-shadow-color . "#fffffbeeffff"))
;; TIM|     ((buffers-tab-face . buffers-tab)
;; TIM|      (cperl-here-face . font-lock-string-face)
;; TIM|      (cperl-invalid-face quote default)
;; TIM|      (cperl-pod-face . font-lock-comment-face)
;; TIM|      (cperl-pod-head-face . font-lock-variable-name-face)
;; TIM|      (ispell-highlight-face . highlight)
;; TIM|      (vc-mode-face . highlight)
;; TIM|      (vm-highlight-url-face . bold-italic)
;; TIM|      (vm-highlighted-header-face . bold)
;; TIM|      (vm-mime-button-face . gui-button-face)
;; TIM|      (vm-summary-highlight-face . bold))
;; TIM|     (default ((t (nil))))
;; TIM|     (bbdb-company ((t (nil))))
;; TIM|     (bbdb-field-name ((t (:bold t))))
;; TIM|     (bbdb-field-value ((t (nil))))
;; TIM|     (bbdb-name ((t (:underline t))))
;; TIM|     (blue ((t (:foreground "SteelBlue1"))))
;; TIM|     (bold ((t (:bold t))))
;; TIM|     (bold-italic ((t (:bold t :foreground "yellow"))))
;; TIM|     (border-glyph ((t (nil))))
;; TIM|     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
;; TIM|     (cperl-array-face ((t (:bold t :foreground "SkyBlue2"))))
;; TIM|     (cperl-hash-face ((t (:foreground "LightBlue2"))))
;; TIM|     (cperl-invalid-face ((t (:foreground "white"))))
;; TIM|     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
;; TIM|     (custom-button-face ((t (:bold t))))
;; TIM|     (custom-changed-face ((t (:background "SteelBlue1" :foreground "white"))))
;; TIM|     (custom-comment-face ((t (:foreground "white"))))
;; TIM|     (custom-comment-tag-face ((t (:foreground "white"))))
;; TIM|     (custom-documentation-face ((t (nil))))
;; TIM|     (custom-face-tag-face ((t (:underline t))))
;; TIM|     (custom-group-tag-face ((t (:underline t :foreground "SteelBlue1"))))
;; TIM|     (custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
;; TIM|     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
;; TIM|     (custom-modified-face ((t (:background "SteelBlue1" :foreground "white"))))
;; TIM|     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
;; TIM|     (custom-saved-face ((t (:underline t))))
;; TIM|     (custom-set-face ((t (:background "white" :foreground "SteelBlue1"))))
;; TIM|     (custom-state-face ((t (:foreground "white"))))
;; TIM|     (custom-variable-button-face ((t (:underline t :bold t))))
;; TIM|     (custom-variable-tag-face ((t (:underline t :foreground "SteelBlue1"))))
;; TIM|     (cvs-filename-face ((t (:foreground "white"))))
;; TIM|     (cvs-handled-face ((t (:foreground "pink"))))
;; TIM|     (cvs-header-face ((t (:foreground "green"))))
;; TIM|     (cvs-marked-face ((t (:bold t :foreground "green3"))))
;; TIM|     (cvs-msg-face ((t (:foreground "red"))))
;; TIM|     (cvs-need-action-face ((t (:foreground "yellow"))))
;; TIM|     (cvs-unknown-face ((t (:foreground "grey"))))
;; TIM|     (diff-added-face ((t (nil))))
;; TIM|     (diff-changed-face ((t (nil))))
;; TIM|     (diff-file-header-face ((t (:bold t :background "grey70"))))
;; TIM|     (diff-hunk-header-face ((t (:background "grey85"))))
;; TIM|     (diff-index-face ((t (:bold t :background "grey70"))))
;; TIM|     (diff-removed-face ((t (nil))))
;; TIM|     (dired-face-boring ((t (:foreground "Gray65"))))
;; TIM|     (dired-face-directory ((t (:bold t :foreground "SkyBlue2"))))
;; TIM|     (dired-face-executable ((t (:foreground "Green"))))
;; TIM|     (dired-face-flagged ((t (:background "LightSlateGray"))))
;; TIM|     (dired-face-header ((t (:background "grey75" :foreground "black"))))
;; TIM|     (dired-face-marked ((t (:background "PaleVioletRed"))))
;; TIM|     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
;; TIM|     (dired-face-setuid ((t (:foreground "Red"))))
;; TIM|     (dired-face-socket ((t (:foreground "magenta"))))
;; TIM|     (dired-face-symlink ((t (:foreground "cyan"))))
;; TIM|     (excerpt ((t (nil))))
;; TIM|     (fixed ((t (:bold t))))
;; TIM|     (font-lock-builtin-face ((t (:foreground "red3"))))
;; TIM|     (font-lock-comment-face ((t (:foreground "LightGray"))))
;; TIM|     (font-lock-constant-face ((t (nil))))
;; TIM|     (font-lock-doc-string-face ((t (:foreground "turquoise"))))
;; TIM|     (font-lock-function-name-face ((t (:foreground "white"))))
;; TIM|     (font-lock-keyword-face ((t (:foreground "green"))))
;; TIM|     (font-lock-preprocessor-face ((t (:foreground "green3"))))
;; TIM|     (font-lock-reference-face ((t (:foreground "red3"))))
;; TIM|     (font-lock-string-face ((t (:foreground "turquoise"))))
;; TIM|     (font-lock-type-face ((t (:foreground "steelblue"))))
;; TIM|     (font-lock-variable-name-face ((t (:foreground "magenta2"))))
;; TIM|     (font-lock-warning-face ((t (:bold t :foreground "Red"))))
;; TIM|     (green ((t (:foreground "green"))))
;; TIM|     (gui-button-face ((t (:background "grey75" :foreground "black"))))
;; TIM|     (gui-element ((t (nil))))
;; TIM|     (highlight ((t (:background "darkseagreen2" :foreground "SteelBlue1"))))
;; TIM|     (html-helper-bold-face ((t (:bold t))))
;; TIM|     (html-helper-italic-face ((t (:bold t :foreground "yellow"))))
;; TIM|     (html-helper-underline-face ((t (:underline t))))
;; TIM|     (hyper-apropos-documentation ((t (:foreground "white"))))
;; TIM|     (hyper-apropos-heading ((t (:bold t))))
;; TIM|     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
;; TIM|     (hyper-apropos-major-heading ((t (:bold t))))
;; TIM|     (hyper-apropos-section-heading ((t (:bold t))))
;; TIM|     (hyper-apropos-warning ((t (:bold t :foreground "red"))))
;; TIM|     (info-node ((t (:bold t :foreground "yellow"))))
;; TIM|     (info-xref ((t (:bold t))))
;; TIM|     (isearch ((t (:background "paleturquoise" :foreground "dark red"))))
;; TIM|     (isearch-secondary ((t (:foreground "red3"))))
;; TIM|     (italic ((t (:bold t :foreground "yellow"))))
;; TIM|     (left-margin ((t (nil))))
;; TIM|     (list-mode-item-selected ((t (:background "gray68" :foreground "dark green"))))
;; TIM|     (man-bold ((t (:bold t))))
;; TIM|     (man-heading ((t (:bold t))))
;; TIM|     (man-italic ((t (:foreground "yellow"))))
;; TIM|     (man-xref ((t (:underline t))))
;; TIM|     (message-cited-text ((t (:foreground "orange"))))
;; TIM|     (message-header-contents ((t (:foreground "white"))))
;; TIM|     (message-headers ((t (:bold t :foreground "orange"))))
;; TIM|     (message-highlighted-header-contents ((t (:bold t))))
;; TIM|     (message-url ((t (:bold t :foreground "pink"))))
;; TIM|     (mmm-face ((t (:background "black" :foreground "green"))))
;; TIM|     ; (modeline ((t (:background "LightYellow" :foreground "DarkBlue" :bold t))))
;; TIM|     ; (modeline-buffer-id ((t (:background "Gray80" :foreground "SteelBlue4"))))
;; TIM|     ; (modeline-mousable ((t (:background "Gray80" :foreground "firebrick"))))
;; TIM|     ; (modeline-mousable-minor-mode ((t (:background "Gray80" :foreground "green4"))))
;; TIM|     (paren-blink-off ((t (:foreground "gray80"))))
;; TIM|     (paren-match ((t (:background "dark blue"))))
;; TIM|     (paren-mismatch ((t (:background "DeepPink" :foreground "LightSkyBlue"))))
;; TIM|     (pointer ((t (nil))))
;; TIM|     (primary-selection ((t (:background "gray65" :foreground "DarkBlue"))))
;; TIM|     (red ((t (:foreground "red"))))
;; TIM|     (region ((t (:background "gray65" :foreground "DarkBlue"))))
;; TIM|     (right-margin ((t (nil))))
;; TIM|     (secondary-selection ((t (:background "paleturquoise" :foreground "black"))))
;; TIM|     (shell-option-face ((t (:foreground "SteelBlue4"))))
;; TIM|     (shell-output-2-face ((t (:foreground "green4"))))
;; TIM|     (shell-output-3-face ((t (:foreground "green4"))))
;; TIM|     (shell-output-face ((t (:bold t))))
;; TIM|     (shell-prompt-face ((t (:foreground "red4"))))
;; TIM|     (text-cursor ((t (:background "Red3" :foreground "black"))))
;; TIM|     (toolbar ((t (:background "Gray80" :foreground "black"))))
;; TIM|     (underline ((t (:underline t))))
;; TIM|     (vertical-divider ((t (nil))))
;; TIM|     (vm-xface ((t (:background "white" :foreground "black"))))
;; TIM|     (vmpc-pre-sig-face ((t (:foreground "forestgreen"))))
;; TIM|     (vmpc-sig-face ((t (:foreground "steelblue"))))
;; TIM|     (widget ((t (nil))))
;; TIM|     (widget-button-face ((t (:bold t))))
;; TIM|     (widget-button-pressed-face ((t (:foreground "red"))))
;; TIM|     (widget-documentation-face ((t (:foreground "dark green"))))
;; TIM|     (widget-field-face ((t (:background "gray85" :foreground "black"))))
;; TIM|     (widget-inactive-face ((t (:foreground "dim gray"))))
;; TIM|     (x-face ((t (:background "white" :foreground "black"))))
;; TIM|     (xrdb-option-name-face ((t (:foreground "red"))))
;; TIM|     (yellow ((t (:foreground "yellow"))))
;; TIM|     (nxml-name-face ((t (:foreground "LightBlue"))))
;; TIM|     (nxml-text-face ((t (:foreground "Heather"))))
;; TIM|     (nxml-comment-content-face ((t (:foreground "Gray80"))))
;; TIM|     (nxml-delimited-data-face ((t (:foreground "Heather"))))
;; TIM|     (zmacs-region ((t (:background "gray65")))))))
